#!/bin/bash

relation-set private-address=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}'|head -n 1`

base=`dirname $0`

UNIT_NAME=`echo $JUJU_UNIT_NAME | cut -d/ -f1`
UNIT_DIR=/srv/${UNIT_NAME}

DB_USER=$(relation-get user)
DB_PASSWORD=$(relation-get password)
DB_HOST=$(relation-get host)
DB_DATABASE=$(relation-get database)

name=`basename $0`

juju-log "Executing $name"

if [ -z "$DB_USER" ] ; then
    juju-log "No database information yet."
    exit 0 # wait for future handshake from database service unit
fi

cat > ${UNIT_DIR}/db_settings.py << EOF
# Settings for database connexion

DATABASES = {
    "default": {
        "ENGINE": 'django.db.backends.postgresql_psycopg2',
        "NAME": '$DB_DATABASE',
        "USER": '$DB_USER',
        "PASSWORD": '$DB_PASSWORD',
        "HOST": '$DB_HOST',
        "PORT": '',
    }
}

EOF


python ${UNIT_DIR}/manage.py syncdb --noinput
python ${UNIT_DIR}/manage.py migrate --noinput

chown www-data ${UNIT_DIR} -R
chmod g+rw ${UNIT_DIR} -R

exec $base/config-changed

/etc/init.d/gunicorn start
/etc/init.d/gunicorn reload
